In [1]:
import numpy as np

In [14]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
x,y

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

Operations:

In [15]:
x + y

array([ 6,  8, 10, 12])

In [16]:
x -y 

array([-4, -4, -4, -4])

In [18]:
x * y

array([ 5, 12, 21, 32])

In [19]:
D = np.dot(x,y)
D

70

In [20]:
x.T

array([1, 2, 3, 4])

In [26]:
x_list = [1,2,3,4]
y_list = [5,6,7,8]
x_list + y_list

[1, 2, 3, 4, 5, 6, 7, 8]

In [27]:
x_list * y_list

TypeError: can't multiply sequence by non-int of type 'list'

In [28]:
A_list = [a + b for a,b in zip(x_list,y_list)]
print(A_list)
x + y

[6, 8, 10, 12]


array([ 6,  8, 10, 12])

# Shape

In [31]:
print(x)
x.shape

[1 2 3 4]


(4,)

In [34]:
D = np.dot(x,y)
type(D), D.shape

(numpy.int64, ())

# Matrices

In [37]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [38]:
A.shape

(2, 2)

In [40]:
B = np.array([[1,3],[2,4]])

In [41]:
A * B 

array([[ 1,  6],
       [ 6, 16]])

In [42]:
A + B

array([[2, 5],
       [5, 8]])

In [43]:
np.dot(A,B)

array([[ 5, 11],
       [11, 25]])

In [44]:
A@B

array([[ 5, 11],
       [11, 25]])

In [46]:
A = np.array([[1,3, 5],[2,4, 6]])
A

array([[1, 3, 5],
       [2, 4, 6]])

In [48]:
B = np.array([[1,3],[2,4],[5,6]])
B

array([[1, 3],
       [2, 4],
       [5, 6]])

In [52]:
np.dot(A,A)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [57]:
A = np.array([[1,3],[2,4]])
A
np.linalg.det(A)

-2.0

In [59]:
np.max(A), A

(4, array([[1, 3],
        [2, 4]]))

In [60]:
np.average(A)

2.5

In [61]:
np.std(A)

1.118033988749895

# Special Array Initialization

In [63]:
A = np.zeros((6,6))
A

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [66]:
B = np.ones((3,3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [70]:
C = np.diag((1, 2, 3))
C

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [73]:
D = np.eye(10)
D

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [74]:
E = np.random.rand(3,3)
E

array([[0.70416996, 0.24809511, 0.39947397],
       [0.04430073, 0.7584805 , 0.62543659],
       [0.11355495, 0.60580345, 0.31346631]])

In [77]:
F = np.triu(B)
F

array([[1., 1., 1.],
       [0., 1., 1.],
       [0., 0., 1.]])

# Array Types

In [78]:
A = np.ones((2,2))
type(A), A.shape, A.size, A.ndim, A.dtype

(numpy.ndarray, (2, 2), 4, 2, dtype('float64'))

In [79]:
B = np.ones((3,3,3))
type(B), B.shape, B.size, B.ndim, B.dtype

(numpy.ndarray, (3, 3, 3), 27, 3, dtype('float64'))

# Casting

In [81]:
E = A.astype("float32")
E.dtype

dtype('float32')

In [83]:
B = A.astype(int)
B

array([[1, 1],
       [1, 1]])

# Array Rearanging

In [84]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
AA = np.reshape(A,())

In [91]:
AA = np.reshape(A,(6))
AA.shape, AA.ndim

((6,), 1)

In [98]:
AA

array([[1, 2, 3, 4, 5, 6]])

In [96]:
AA = np.reshape(A,(1,6))
AA.shape, AA.ndim

((1, 6), 2)

In [103]:
X = np.random.rand(10,10)
X.shape

(10, 10)

In [102]:
XX = X.ravel()
XX.shape

(100,)

array([0.29888077, 0.29672034, 0.303517  , 0.01934397, 0.07067084,
       0.61672162, 0.31226764, 0.8896621 , 0.3750965 , 0.81813493,
       0.8944569 , 0.21694537, 0.13591852, 0.52204266, 0.54244228,
       0.04191421, 0.25515047, 0.3701969 , 0.31583418, 0.16868798,
       0.48466309, 0.20536607, 0.59116598, 0.55105522, 0.59441685,
       0.14251113, 0.41391458, 0.71324627, 0.99942611, 0.23987449,
       0.98907192, 0.01889464, 0.41836149, 0.40497791, 0.58617707,
       0.59094673, 0.47481992, 0.99982054, 0.20903541, 0.53182197,
       0.63498628, 0.6092637 , 0.52966264, 0.19826927, 0.07730794,
       0.95082056, 0.2971576 , 0.36967812, 0.86521864, 0.85892503,
       0.11366249, 0.2124359 , 0.75375447, 0.66200302, 0.83441991,
       0.16436956, 0.95388402, 0.86578258, 0.4296128 , 0.80501615,
       0.0565061 , 0.82004261, 0.20613371, 0.40098008, 0.34637326,
       0.97394144, 0.50363877, 0.27020265, 0.38165465, 0.16604334,
       0.45344968, 0.8190722 , 0.75343275, 0.89015131, 0.62692

In [110]:
X = np.ones((3,3,3,3))


In [112]:
XX = X.reshape((3,3,-1))
XX.shape

(3, 3, 9)

# Broadcasting

In [114]:
a = np.array([[2,4],[6,7]])
a

array([[2, 4],
       [6, 7]])

In [115]:
a + 6

array([[ 8, 10],
       [12, 13]])

In [116]:
six = np.array([[6,6],[6,6]])

In [117]:
a + six

array([[ 8, 10],
       [12, 13]])

In [118]:
a - 6

array([[-4, -2],
       [ 0,  1]])

In [130]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((2,4))

x.shape,xx.shape,y.shape,z.shape

((4,), (4, 1), (5,), (2, 4))

In [137]:
xx.shape, z.T.shape

((4, 1), (4, 2))

In [126]:
(xx + y).shape

(4, 5)

In [125]:
xx.shape, y.shape

((4, 1), (5,))

![](numpy_broadcasting.png)

In [136]:
x + z

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.]])

# Indexing

In [138]:
A = np.arange(30).reshape(6,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [139]:
A.shape

(6, 5)

In [145]:
A[0:3,0:3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [141]:
A[0]

array([0, 1, 2, 3, 4])

In [146]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [147]:
A[1::2]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [148]:
B = np.arange(6)
B

array([0, 1, 2, 3, 4, 5])

In [149]:
mask = np.array([True,False,True,True,False,True])
mask

array([ True, False,  True,  True, False,  True])

In [150]:
B[mask]

array([0, 2, 3, 5])

In [151]:
B

array([0, 1, 2, 3, 4, 5])

In [152]:
B > 3

array([False, False, False, False,  True,  True])

In [153]:
mask = B > 3
B[mask]

array([4, 5])

In [155]:
a = np.random.rand(4,4)
a

array([[0.37697668, 0.71963144, 0.4391184 , 0.67921441],
       [0.11540106, 0.2935868 , 0.67681938, 0.74037564],
       [0.15884522, 0.80515255, 0.93535141, 0.05460755],
       [0.05184734, 0.59241049, 0.38565198, 0.41604317]])

In [159]:
b = a > 0.5
b

array([[False,  True, False,  True],
       [False, False,  True,  True],
       [False,  True,  True, False],
       [False,  True, False, False]])

In [160]:
A = np.arange(30).reshape(5,6)
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [166]:
indices_row = [1,3,4]
indices_col = [2,4,5]
A[indices_row, indices_col]

array([ 8, 22, 29])

# Boolean Functions 

In [175]:
A = np.arange(5)
np.any(A > 4)

False

In [176]:
np.all(A > 3)

False

In [205]:
A = np.arange(30).reshape(5,6)
A = A +10

In [186]:
np.any(A%5==3,axis=0)

array([ True, False, False,  True,  True,  True, False, False,  True])

In [192]:
np.sum(A,axis=1)

array([ 15,  51,  87, 123, 159])

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [208]:
np.argmax(A)

29

In [209]:
np.nonzero(A==39)

(array([4]), array([5]))

In [1]:
import numpy as np

In [12]:
x = np.arange(100)
x = x.reshape(5,5,-1)
x.shape

(5, 5, 4)

In [13]:
x = np.random.rand((100,100))
y = np.random.rand(100)
y = np.asarray(y,dtype=bool)
y
mask =  0.3 > 
x





SyntaxError: invalid syntax (<ipython-input-13-dd4a5633a1ef>, line 2)